apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
    service: web-app
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
