apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-service
    service: book-service
  name: book-service
  namespace: kind-local
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: book-service
  type: ClusterIP